server:
  port: 9300
spring:

  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ayocar
    password: 123456
    url: jdbc:mysql://183.3.158.22:3306/exam?useUnicode=true&characterEncoding=utf-8

  redis:
    host: 183.3.158.22
    database: 0
    port: 6379
    password: Wvk3Iu
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        min-idle: 10
    timeout: 1000

  mybatis:
    type-aliases-package: cn.zk.exam.dao
